github: dneverson
buy_me_a_coffee: dnepixela
custom:
  - 'https://paypal.me/LegionProgramming'
  - 'https://venmo.com/code?user_id=3541143333635845657&created=1783179354'
  - 'https://cash.app/$DerryEverson'
